---
version: "3.8"
services:
    keyed:
        image: ayay2021/keyed.sh
        container_name: keyed
        ports:
            - 800:80
        volumes:
            - /run/media/lain/data/server_configs/basedtube/cdn:/var/www/cdn
        environment:
            - CDN_DOMAIN=https://cdn.keyed.sh
            - MAIN_DOMAIN=https://keyed.sh
            - BRANDING=keyed.sh
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=tube
        restart: always
        depends_on:
            - db
            
    db:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=postgres
        restart: always
