---
version: "3.8"
services:
    keyed.sh:
        image: keyed.sh
        container_name: keyed.sh
        ports:
            - 80:80
            - 443:443
        volumes:
            - /run/media/lain/data/server_configs/basedtube/cdn:/var/www/cdn
            - /run/media/lain/data/server_configs/basedtube/letsencrypt:/etc/letsencrypt
        environment:
            - CDN_DOMAIN=https://cdn.keyed.sh
            - MAIN_DOMAIN=https://keyed.sh
            - BRANDING=keyed.sh
            - SITE_VERSION=v1.51
        restart: always
        depends_on:
            - db
            
    db:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123
        restart: always
